# Generated by Django 3.0.5 on 2021-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestblooddonationrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
