# Generated by Django 3.0.5 on 2021-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_requestblooddonationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestblooddonationrequest',
            name='hospitalID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='requestblooddonationrequest',
            name='hospitalName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
