# Generated by Django 3.0.5 on 2021-05-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
    ]
