# Generated by Django 3.0.5 on 2021-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_bloodrequest_hospitalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospitalID',
            field=models.CharField(max_length=30),
        ),
    ]
