# Generated by Django 3.0.5 on 2021-05-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_auto_20210511_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequestbyhospital',
            name='hospitalID',
        ),
        migrations.RemoveField(
            model_name='bloodrequestbyhospital',
            name='hospital_name',
        ),
    ]
