# Generated by Django 3.0.5 on 2021-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_auto_20210511_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequestbyhospital',
            name='hospitalID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodrequestbyhospital',
            name='hospitalName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
