# Generated by Django 3.0.5 on 2021-05-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_auto_20210511_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status_hospital',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
